#AWS settings

# AWS_ACCESS_KEY_ID = 'AKIAIQV5OYFEVOZBC5JQ'
# AWS_SECRET_ACCESS_KEY = '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'

#Email settings

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'titiphotos593@gmail.com'
EMAIL_HOST_PASSWORD = 'Bl@zetr@il'
EMAIL_PORT = 587
EMAIL_USE_TLS = True